# enables discord
enableDiscord: false
# discord bot token - never show that token to anyone - it is a username and passowrd for your bot in one
botToken: null
# discord bot prefix - replace if you want to change from /
botPrefix: '/'
# a list of roles allowed to whitelist through discord. Example:
############################
# allowedRoleIds:          #
#   - '760522213676941332' #
#   - '850019046345801768' #
#   - '701844438153953420' #
#   - '722064316479701083' #
#   - '748533112404705281' #
#   - '819296501451980820' #
#   - '707915540085342248' #
#   - '759456739669704784' #
#   - '749576790929965136' #
#   - '702925135568437270' #
############################
allowedRoleIds:
  - role: null
# a list of roles allowed to whiteban through discord - ingame the whitelist.listban permission is used. Example:
############################
# allowedModRoleIds:       #
#   - '760522213676941332' #
#   - '822957506674163792' #
############################
allowedModRoleIds:
  - null
# should a discord channel be linked with ingame chat
linkChannels: false
# channel id of the linked discord channel
channelLinkId: null
# the message that gets displayed ingame when an online member gets banned (minecrafts color coding should still work here)
banMessage: 'Thou hast been banned™'
# the message that gets displayed when a user is not whitelisted (minecrafts color coding should still work here)
connectionFailMessage: 'You are not whitelisted'